package com.zero.blog.entity;

public class ZBlogGr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_gr.gr_id
     *
     * @mbggenerated
     */
    private Long grId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_gr.g_id
     *
     * @mbggenerated
     */
    private Long gId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_gr.r_id
     *
     * @mbggenerated
     */
    private Long rId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_gr.gr_id
     *
     * @return the value of z_blog_gr.gr_id
     *
     * @mbggenerated
     */
    public Long getGrId() {
        return grId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_gr.gr_id
     *
     * @param grId the value for z_blog_gr.gr_id
     *
     * @mbggenerated
     */
    public void setGrId(Long grId) {
        this.grId = grId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_gr.g_id
     *
     * @return the value of z_blog_gr.g_id
     *
     * @mbggenerated
     */
    public Long getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_gr.g_id
     *
     * @param gId the value for z_blog_gr.g_id
     *
     * @mbggenerated
     */
    public void setgId(Long gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_gr.r_id
     *
     * @return the value of z_blog_gr.r_id
     *
     * @mbggenerated
     */
    public Long getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_gr.r_id
     *
     * @param rId the value for z_blog_gr.r_id
     *
     * @mbggenerated
     */
    public void setrId(Long rId) {
        this.rId = rId;
    }
}