package com.zero.blog.entity;

import java.util.Date;

public class ZBlogOperationLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_operation_log.log_id
     *
     * @mbggenerated
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_operation_log.operation_type
     *
     * @mbggenerated
     */
    private Integer operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_operation_log.operation_content
     *
     * @mbggenerated
     */
    private String operationContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_operation_log.operation_person
     *
     * @mbggenerated
     */
    private Long operationPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_operation_log.operation_create
     *
     * @mbggenerated
     */
    private Date operationCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_operation_log.log_id
     *
     * @return the value of z_blog_operation_log.log_id
     *
     * @mbggenerated
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_operation_log.log_id
     *
     * @param logId the value for z_blog_operation_log.log_id
     *
     * @mbggenerated
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_operation_log.operation_type
     *
     * @return the value of z_blog_operation_log.operation_type
     *
     * @mbggenerated
     */
    public Integer getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_operation_log.operation_type
     *
     * @param operationType the value for z_blog_operation_log.operation_type
     *
     * @mbggenerated
     */
    public void setOperationType(Integer operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_operation_log.operation_content
     *
     * @return the value of z_blog_operation_log.operation_content
     *
     * @mbggenerated
     */
    public String getOperationContent() {
        return operationContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_operation_log.operation_content
     *
     * @param operationContent the value for z_blog_operation_log.operation_content
     *
     * @mbggenerated
     */
    public void setOperationContent(String operationContent) {
        this.operationContent = operationContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_operation_log.operation_person
     *
     * @return the value of z_blog_operation_log.operation_person
     *
     * @mbggenerated
     */
    public Long getOperationPerson() {
        return operationPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_operation_log.operation_person
     *
     * @param operationPerson the value for z_blog_operation_log.operation_person
     *
     * @mbggenerated
     */
    public void setOperationPerson(Long operationPerson) {
        this.operationPerson = operationPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_operation_log.operation_create
     *
     * @return the value of z_blog_operation_log.operation_create
     *
     * @mbggenerated
     */
    public Date getOperationCreate() {
        return operationCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_operation_log.operation_create
     *
     * @param operationCreate the value for z_blog_operation_log.operation_create
     *
     * @mbggenerated
     */
    public void setOperationCreate(Date operationCreate) {
        this.operationCreate = operationCreate;
    }
}