package com.zero.blog.entity;

public class ZBlogUr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_ur.ur_id
     *
     * @mbggenerated
     */
    private Long urId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_ur.u_id
     *
     * @mbggenerated
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_ur.r_id
     *
     * @mbggenerated
     */
    private Long rId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_ur.ur_id
     *
     * @return the value of z_blog_ur.ur_id
     *
     * @mbggenerated
     */
    public Long getUrId() {
        return urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_ur.ur_id
     *
     * @param urId the value for z_blog_ur.ur_id
     *
     * @mbggenerated
     */
    public void setUrId(Long urId) {
        this.urId = urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_ur.u_id
     *
     * @return the value of z_blog_ur.u_id
     *
     * @mbggenerated
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_ur.u_id
     *
     * @param uId the value for z_blog_ur.u_id
     *
     * @mbggenerated
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_ur.r_id
     *
     * @return the value of z_blog_ur.r_id
     *
     * @mbggenerated
     */
    public Long getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_ur.r_id
     *
     * @param rId the value for z_blog_ur.r_id
     *
     * @mbggenerated
     */
    public void setrId(Long rId) {
        this.rId = rId;
    }
}