package com.zero.blog.entity;

public class ZBlogUg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_ug.ug_id
     *
     * @mbggenerated
     */
    private Long ugId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_ug.u_id
     *
     * @mbggenerated
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_ug.g_id
     *
     * @mbggenerated
     */
    private Long gId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_ug.ug_id
     *
     * @return the value of z_blog_ug.ug_id
     *
     * @mbggenerated
     */
    public Long getUgId() {
        return ugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_ug.ug_id
     *
     * @param ugId the value for z_blog_ug.ug_id
     *
     * @mbggenerated
     */
    public void setUgId(Long ugId) {
        this.ugId = ugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_ug.u_id
     *
     * @return the value of z_blog_ug.u_id
     *
     * @mbggenerated
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_ug.u_id
     *
     * @param uId the value for z_blog_ug.u_id
     *
     * @mbggenerated
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_ug.g_id
     *
     * @return the value of z_blog_ug.g_id
     *
     * @mbggenerated
     */
    public Long getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_ug.g_id
     *
     * @param gId the value for z_blog_ug.g_id
     *
     * @mbggenerated
     */
    public void setgId(Long gId) {
        this.gId = gId;
    }
}