package com.zero.blog.entity;

import java.util.Date;

public class ZBlogUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_user.u_id
     *
     * @mbggenerated
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_user.o_id
     *
     * @mbggenerated
     */
    private Long oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_user.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_user.login_password
     *
     * @mbggenerated
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_user.u_name
     *
     * @mbggenerated
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_user.u_phone
     *
     * @mbggenerated
     */
    private String uPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_user.u_email
     *
     * @mbggenerated
     */
    private String uEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_user.u_create
     *
     * @mbggenerated
     */
    private Date uCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_user.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_user.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_user.login_count
     *
     * @mbggenerated
     */
    private Long loginCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_user.u_id
     *
     * @return the value of z_blog_user.u_id
     *
     * @mbggenerated
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_user.u_id
     *
     * @param uId the value for z_blog_user.u_id
     *
     * @mbggenerated
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_user.o_id
     *
     * @return the value of z_blog_user.o_id
     *
     * @mbggenerated
     */
    public Long getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_user.o_id
     *
     * @param oId the value for z_blog_user.o_id
     *
     * @mbggenerated
     */
    public void setoId(Long oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_user.login_name
     *
     * @return the value of z_blog_user.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_user.login_name
     *
     * @param loginName the value for z_blog_user.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_user.login_password
     *
     * @return the value of z_blog_user.login_password
     *
     * @mbggenerated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_user.login_password
     *
     * @param loginPassword the value for z_blog_user.login_password
     *
     * @mbggenerated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_user.u_name
     *
     * @return the value of z_blog_user.u_name
     *
     * @mbggenerated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_user.u_name
     *
     * @param uName the value for z_blog_user.u_name
     *
     * @mbggenerated
     */
    public void setuName(String uName) {
        this.uName = uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_user.u_phone
     *
     * @return the value of z_blog_user.u_phone
     *
     * @mbggenerated
     */
    public String getuPhone() {
        return uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_user.u_phone
     *
     * @param uPhone the value for z_blog_user.u_phone
     *
     * @mbggenerated
     */
    public void setuPhone(String uPhone) {
        this.uPhone = uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_user.u_email
     *
     * @return the value of z_blog_user.u_email
     *
     * @mbggenerated
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_user.u_email
     *
     * @param uEmail the value for z_blog_user.u_email
     *
     * @mbggenerated
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_user.u_create
     *
     * @return the value of z_blog_user.u_create
     *
     * @mbggenerated
     */
    public Date getuCreate() {
        return uCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_user.u_create
     *
     * @param uCreate the value for z_blog_user.u_create
     *
     * @mbggenerated
     */
    public void setuCreate(Date uCreate) {
        this.uCreate = uCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_user.login_time
     *
     * @return the value of z_blog_user.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_user.login_time
     *
     * @param loginTime the value for z_blog_user.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_user.last_login_time
     *
     * @return the value of z_blog_user.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_user.last_login_time
     *
     * @param lastLoginTime the value for z_blog_user.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_user.login_count
     *
     * @return the value of z_blog_user.login_count
     *
     * @mbggenerated
     */
    public Long getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_user.login_count
     *
     * @param loginCount the value for z_blog_user.login_count
     *
     * @mbggenerated
     */
    public void setLoginCount(Long loginCount) {
        this.loginCount = loginCount;
    }
}