package com.zero.blog.entity;

public class ZBlogRp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_rp.rp_id
     *
     * @mbggenerated
     */
    private Long rpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_rp.r_id
     *
     * @mbggenerated
     */
    private Long rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_rp.p_id
     *
     * @mbggenerated
     */
    private Long pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_rp.p_type
     *
     * @mbggenerated
     */
    private Integer pType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_rp.rp_id
     *
     * @return the value of z_blog_rp.rp_id
     *
     * @mbggenerated
     */
    public Long getRpId() {
        return rpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_rp.rp_id
     *
     * @param rpId the value for z_blog_rp.rp_id
     *
     * @mbggenerated
     */
    public void setRpId(Long rpId) {
        this.rpId = rpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_rp.r_id
     *
     * @return the value of z_blog_rp.r_id
     *
     * @mbggenerated
     */
    public Long getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_rp.r_id
     *
     * @param rId the value for z_blog_rp.r_id
     *
     * @mbggenerated
     */
    public void setrId(Long rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_rp.p_id
     *
     * @return the value of z_blog_rp.p_id
     *
     * @mbggenerated
     */
    public Long getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_rp.p_id
     *
     * @param pId the value for z_blog_rp.p_id
     *
     * @mbggenerated
     */
    public void setpId(Long pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_rp.p_type
     *
     * @return the value of z_blog_rp.p_type
     *
     * @mbggenerated
     */
    public Integer getpType() {
        return pType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_rp.p_type
     *
     * @param pType the value for z_blog_rp.p_type
     *
     * @mbggenerated
     */
    public void setpType(Integer pType) {
        this.pType = pType;
    }
}