package com.zero.blog.entity;

public class ZBlogAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_authority.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_authority.permission_name
     *
     * @mbggenerated
     */
    private String permissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_authority.permission_parent_id
     *
     * @mbggenerated
     */
    private Long permissionParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_authority.permission_description
     *
     * @mbggenerated
     */
    private String permissionDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_authority.id
     *
     * @return the value of z_blog_authority.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_authority.id
     *
     * @param id the value for z_blog_authority.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_authority.permission_name
     *
     * @return the value of z_blog_authority.permission_name
     *
     * @mbggenerated
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_authority.permission_name
     *
     * @param permissionName the value for z_blog_authority.permission_name
     *
     * @mbggenerated
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_authority.permission_parent_id
     *
     * @return the value of z_blog_authority.permission_parent_id
     *
     * @mbggenerated
     */
    public Long getPermissionParentId() {
        return permissionParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_authority.permission_parent_id
     *
     * @param permissionParentId the value for z_blog_authority.permission_parent_id
     *
     * @mbggenerated
     */
    public void setPermissionParentId(Long permissionParentId) {
        this.permissionParentId = permissionParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_authority.permission_description
     *
     * @return the value of z_blog_authority.permission_description
     *
     * @mbggenerated
     */
    public String getPermissionDescription() {
        return permissionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_authority.permission_description
     *
     * @param permissionDescription the value for z_blog_authority.permission_description
     *
     * @mbggenerated
     */
    public void setPermissionDescription(String permissionDescription) {
        this.permissionDescription = permissionDescription;
    }
}