package com.zero.blog.entity;

public class ZBlogRg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_rg.gr_id
     *
     * @mbggenerated
     */
    private Long grId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_rg.g_id
     *
     * @mbggenerated
     */
    private Long gId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_rg.p_id
     *
     * @mbggenerated
     */
    private Long pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_rg.p_type
     *
     * @mbggenerated
     */
    private Integer pType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_rg.gr_id
     *
     * @return the value of z_blog_rg.gr_id
     *
     * @mbggenerated
     */
    public Long getGrId() {
        return grId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_rg.gr_id
     *
     * @param grId the value for z_blog_rg.gr_id
     *
     * @mbggenerated
     */
    public void setGrId(Long grId) {
        this.grId = grId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_rg.g_id
     *
     * @return the value of z_blog_rg.g_id
     *
     * @mbggenerated
     */
    public Long getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_rg.g_id
     *
     * @param gId the value for z_blog_rg.g_id
     *
     * @mbggenerated
     */
    public void setgId(Long gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_rg.p_id
     *
     * @return the value of z_blog_rg.p_id
     *
     * @mbggenerated
     */
    public Long getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_rg.p_id
     *
     * @param pId the value for z_blog_rg.p_id
     *
     * @mbggenerated
     */
    public void setpId(Long pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_rg.p_type
     *
     * @return the value of z_blog_rg.p_type
     *
     * @mbggenerated
     */
    public Integer getpType() {
        return pType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_rg.p_type
     *
     * @param pType the value for z_blog_rg.p_type
     *
     * @mbggenerated
     */
    public void setpType(Integer pType) {
        this.pType = pType;
    }
}