package com.zero.blog.entity;

import java.util.Date;

public class ZBlogGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_group.g_id
     *
     * @mbggenerated
     */
    private Long gId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_group.g_name
     *
     * @mbggenerated
     */
    private String gName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_group.g_parent_id
     *
     * @mbggenerated
     */
    private Long gParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_group.g_create
     *
     * @mbggenerated
     */
    private Date gCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_blog_group.g_describe
     *
     * @mbggenerated
     */
    private String gDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_group.g_id
     *
     * @return the value of z_blog_group.g_id
     *
     * @mbggenerated
     */
    public Long getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_group.g_id
     *
     * @param gId the value for z_blog_group.g_id
     *
     * @mbggenerated
     */
    public void setgId(Long gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_group.g_name
     *
     * @return the value of z_blog_group.g_name
     *
     * @mbggenerated
     */
    public String getgName() {
        return gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_group.g_name
     *
     * @param gName the value for z_blog_group.g_name
     *
     * @mbggenerated
     */
    public void setgName(String gName) {
        this.gName = gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_group.g_parent_id
     *
     * @return the value of z_blog_group.g_parent_id
     *
     * @mbggenerated
     */
    public Long getgParentId() {
        return gParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_group.g_parent_id
     *
     * @param gParentId the value for z_blog_group.g_parent_id
     *
     * @mbggenerated
     */
    public void setgParentId(Long gParentId) {
        this.gParentId = gParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_group.g_create
     *
     * @return the value of z_blog_group.g_create
     *
     * @mbggenerated
     */
    public Date getgCreate() {
        return gCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_group.g_create
     *
     * @param gCreate the value for z_blog_group.g_create
     *
     * @mbggenerated
     */
    public void setgCreate(Date gCreate) {
        this.gCreate = gCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_blog_group.g_describe
     *
     * @return the value of z_blog_group.g_describe
     *
     * @mbggenerated
     */
    public String getgDescribe() {
        return gDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_blog_group.g_describe
     *
     * @param gDescribe the value for z_blog_group.g_describe
     *
     * @mbggenerated
     */
    public void setgDescribe(String gDescribe) {
        this.gDescribe = gDescribe;
    }
}