package com.zero.blog.dao;

import com.zero.blog.entity.ZBlogOperationLog;

public interface ZBlogOperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_operation_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_operation_log
     *
     * @mbggenerated
     */
    int insert(ZBlogOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_operation_log
     *
     * @mbggenerated
     */
    int insertSelective(ZBlogOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_operation_log
     *
     * @mbggenerated
     */
    ZBlogOperationLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_operation_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZBlogOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_operation_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZBlogOperationLog record);
}