package com.zero.blog.dao;

import com.zero.blog.entity.ZBlogUser;

public interface ZBlogUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_user
     *
     * @mbggenerated
     */
    int insert(ZBlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_user
     *
     * @mbggenerated
     */
    int insertSelective(ZBlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_user
     *
     * @mbggenerated
     */
    ZBlogUser selectByPrimaryKey(Long uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZBlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZBlogUser record);
}