package com.zero.blog.dao;

import com.zero.blog.entity.ZBlogRole;

public interface ZBlogRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_role
     *
     * @mbggenerated
     */
    int insert(ZBlogRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_role
     *
     * @mbggenerated
     */
    int insertSelective(ZBlogRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_role
     *
     * @mbggenerated
     */
    ZBlogRole selectByPrimaryKey(Long rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZBlogRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZBlogRole record);
}