package com.zero.blog.dao;

import com.zero.blog.entity.ZBlogUg;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ZBlogUgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_ug
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ugId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_ug
     *
     * @mbggenerated
     */
    int insert(ZBlogUg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_ug
     *
     * @mbggenerated
     */
    int insertSelective(ZBlogUg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_ug
     *
     * @mbggenerated
     */
    ZBlogUg selectByPrimaryKey(Long ugId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_ug
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZBlogUg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_ug
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZBlogUg record);
}