package com.zero.blog.dao;

import com.zero.blog.entity.ZBlogGr;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ZBlogGrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_gr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long grId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_gr
     *
     * @mbggenerated
     */
    int insert(ZBlogGr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_gr
     *
     * @mbggenerated
     */
    int insertSelective(ZBlogGr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_gr
     *
     * @mbggenerated
     */
    ZBlogGr selectByPrimaryKey(Long grId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_gr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZBlogGr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_blog_gr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZBlogGr record);
}